[project]
name = "gamecontrollistener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "iterfzf>=1.8.0.62.0",
    "pynput>=1.8.1",
    "vaapi",
]

[tool.uv.sources]
vaapi = { path = "../../sdk" }
