apiVersion: apps/v1
kind: Deployment
metadata:
  name: models-filesystem 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: models-filesystem
  template:
    metadata:
      labels:
        app: models-filesystem
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf3
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf3
          readOnly: true
        - name: modelsmount
          mountPath: /mnt/models
        resources:
          requests:
            memory: "800Mi"
            cpu: "1"
          limits:
            memory: "1000Mi"
            cpu: "2"
      volumes:
      - name: nginx-conf3
        configMap:
          name: nginx-conf3
          items:
            - key: nginx.conf3
              path: nginx.conf3
      - name: modelsmount
        hostPath:
          path: /mnt/models
      revisionHistoryLimit: 3