apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: models-filesystem
  namespace: {{ .Values.namespace }}
  labels:
    app: models-filesystem
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "700m"
    # Enable real IP detection for this ingress
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($http_user_agent ~* (Googlebot|Google-InspectionTool|AdsBot-Google|Mediapartners-Google|Googlebot-Mobile|Googlebot-Image|Googlebot-Video|Googlebot-News|SemrushBot|meta-externalagent|gptbot)) {
        return 403;
      }

    nginx.ingress.kubernetes.io/configuration-snippet: |

      add_header Supports-Loading-Mode "credentialed-prerender";
      add_header Cache-Control "public";
spec:
  ingressClassName: nginx
  rules:
    - host: "models.berlin-united.com"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: models-svc
                port:
                  number: 80
  tls:
  - hosts:
    - "models.berlin-united.com"
    secretName: tls-cert-models
