apiVersion: v2
name: prometheus
description: Berlin United prometheus
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts/prometheus
    version: 27.32.0
