apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docs
  namespace: {{ .Values.namespace }}
  labels:
    app: docs
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "700m"
spec:
  ingressClassName: nginx
  rules:
    - host: "docs.berlin-united.com"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: docs-svc
                port:
                  number: 80
  tls:
  - hosts:
    - "docs.berlin-united.com"
    secretName: tls-cert-docs
