apiVersion: apps/v1
kind: Deployment
metadata:
  name: vat-backend 
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: vat-backend
  template:
    metadata:
      labels:
        app: vat-backend
    spec:
      initContainers:
      - name: django-migrations
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        command: 
        - /bin/sh
        - -c
        - |
          python manage.py migrate
        env:
        - name: USE_POSTGRES
          value: "true"
        - name: VAT_POSTGRES_DB
          value: "vat"
        - name: VAT_POSTGRES_USER
          value: "naoth"
        - name: VAT_POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: "password"
        - name: VAT_POSTGRES_HOST
          value: "postgres-postgresql.postgres.svc.cluster.local"
        - name: VAT_POSTGRES_PORT
          value: "5432"
      containers:
      - name: backend
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        resources:
          requests:
            memory: "4Gi"
            cpu: "10"
          limits:
            memory: "6Gi"
            cpu: "10"
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: "secretkey"
        - name: USE_POSTGRES
          value: "true"
        - name: VAT_POSTGRES_DB
          value: "vat"
        - name: VAT_POSTGRES_USER
          value: "naoth"
        - name: VAT_POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: "password"
        - name: VAT_POSTGRES_HOST
          value: "postgres-postgresql.postgres.svc.cluster.local"
        - name: VAT_POSTGRES_PORT
          value: "5432"
        volumeMounts:
        - name: modelmount
          mountPath: /mnt/models
        - name: datasetmount
          mountPath: /mnt/datasets
      imagePullSecrets:
      - name: github-access
      volumes:
      - name: modelmount
        hostPath:
          path: /mnt/models
      - name: datasetmount
        hostPath:
          path: /mnt/datasets    